# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

require 'google/protobuf/timestamp_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sample.proto", :syntax => :proto3) do
    add_message "sample.SampleMessage" do
      optional :conent, :string, 1
      optional :created_at, :message, 2, "google.protobuf.Timestamp"
    end
  end
end

module Sample
  SampleMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sample.SampleMessage").msgclass
end
