# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

require 'google/protobuf/timestamp_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sample.proto", :syntax => :proto3) do
    add_message "sample.TestMessage" do
      optional :content, :string, 1
      optional :created_at, :message, 2, "google.protobuf.Timestamp"
    end
  end
end

module Sample
  TestMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sample.TestMessage").msgclass
end
